### ISSUE TITLE
remove merge issue

### ISSUE THREAD

**Issue by leonmarkacz** [DSC-DYPCOE/Website#2]
https://github.com/DSC-DYPCOE/Website/blob/3a6d1731287f7213a5d6db3b0b7fe80388e75a32/src/js/custom.js#L1
https://github.com/DSC-DYPCOE/Website/blob/3a6d1731287f7213a5d6db3b0b7fe80388e75a32/src/js/custom.js#L162

**Comment by Abg4real** [comment]
thanks!
