### ISSUE TITLE
Logo change and alignment fixes

### ISSUE THREAD

**Issue by nikhilpawar9** [DSC-DYPCOE/Website#21]
**Describe the bug**
New Logo in **navbar** & **footer** is not updated
Heros section paragraph is not left aligned

**Expected behavior**
New Logo in navbar & footer should be updated
Heros section paragraph should be left aligned

**Screenshots**

![Screenshot 2021-10-02 124616](https://user-images.githubusercontent.com/59965072/135707446-849ebf5c-5761-42c0-b9b0-01761ec028d7.jpg)

**Use this New logo**
![Copy of Copy of GDSC Logo chapter lockup template (2)](https://user-images.githubusercontent.com/59965072/135707553-1867874b-40ce-46b2-b0cb-aa601229096b.png)

**Comment by RohanTheProgrammer** [comment]
![logo](https://user-images.githubusercontent.com/48507690/135707952-4120f585-e411-4305-be20-5a77ad4f3d6f.png)
You want this as logo right ?
logo.png

**Comment by RohanTheProgrammer** [comment]
@nikhilpawar9 
footer-logo.png says `DSC Kisii University`
Should I use it as a footer.
![footer-logo](https://user-images.githubusercontent.com/48507690/135708273-090ccf09-7bd6-4687-baad-8e832b510049.png)

**Comment by nikhilpawar9** [comment]
@RohanTheProgrammer No
I have attached the new logo below screenshot
