### ISSUE TITLE
Updation of Repository links

### ISSUE THREAD

**Issue by AmeyaJain-25** [DSC-DYPCOE/Website#23]
**Describe the bug**
File a bug and View Source links shows 404 error page of GitHub. 

Expected behavior**
It should open the proper link of GitHub repo and issues.

**Additional context**
Up for Grab

**Comment by Fakhri1999** [comment]
can you assign this to me?

**Comment by Fakhri1999** [comment]
solved in PR #26

**Comment by AmeyaJain-25** [comment]
Nice @Fakhri1999
