### ISSUE TITLE
Icons not visible.

### ISSUE THREAD

**Issue by AmeyaJain-25** [DSC-DYPCOE/Website#24]
**Describe the bug**
Scroll to top and slider next and previous icons are not visible.

**Expected behavior**
Icon should be visible in both mobile and desktop view

**Screenshots**
![Screenshot_2021-10-04-21-12-18-521_com android chrome](https://user-images.githubusercontent.com/66305085/135882907-8cbc5757-2436-4ad9-835a-334c1f351b2f.png)

**Additional context**
Up for Grab

**Comment by jonathan-norway** [comment]
Hey, can you assign this to me? I would like to give it a try :)

**Comment by AmeyaJain-25** [comment]
Sure Go for it @jonathan-norway  🚀

**Comment by jonathan-norway** [comment]
Hi, I have tried all devices and different screen ratios, but the icons are always visible. I cannot seem to find the problem. What screen size are you using?

**Comment by AmeyaJain-25** [comment]
Just check for all browsers..
I'm using brave (chromium) i.e Google Chrome.
But check for all browsers

**Comment by AmeyaJain-25** [comment]
Or another best option is you can use svg rather than depending on cdn

**Comment by jonathan-norway** [comment]
Hi, I disassigned myself. I apologize.

**Comment by AmeyaJain-25** [comment]
No issues

**Comment by ShubhamSj07** [comment]
@jonathan-norway , please update your progress
