### ISSUE TITLE
Align cards in Learn section

### ISSUE THREAD

**Issue by AmeyaJain-25** [DSC-DYPCOE/Website#25]
**Describe the bug**
Cards aren't aligned properly in Learn section.

**Expected behavior**
All cards should be look similar.

**Screenshots**
![Screenshot_2021-10-04-21-14-36-038_com android chrome](https://user-images.githubusercontent.com/66305085/135883213-e0285932-5c13-4dd4-89d3-30d0f920b8dc.png)

**Additional context**
Up for Grab

**Comment by inovux** [comment]
Hi can you assign me to this :)?

**Comment by Ashwani132003** [comment]
Hey I will do this, please assign it to me.

**Comment by AmeyaJain-25** [comment]
@inovux Go ahead 👍🏻 


Sorry @Ashwani132003 , as we go with first come first serve, we are assigning it to @inovux . You can try for other issues or for a feature in the website.
