### ISSUE TITLE
Footer not aligned

### ISSUE THREAD

**Issue by JyotiGarde-27** [DSC-DYPCOE/Website#28]
This footer should be at center.
![2021-10-27 (1)](https://user-images.githubusercontent.com/67336818/138954064-63c2036f-6570-4059-a539-d7d9dec584be.png)
.

Please assign me this issue

**Comment by AmeyaJain-25** [comment]
Go ahead @JyotiGarde-27

**Comment by Coder-Himanshu** [comment]
is it fixed or if not let me know will i will do this in 10 minutes and create PR. @JyotiGarde-27

**Comment by AmeyaJain-25** [comment]
Sorry @Coder-Himanshu & @JyotiGarde-27 , this issue is invalid as the page is not from our website. It's the link to the medium DYPCoE GDSC page.
Please look at some other issues
